version: "3.9"
services:
  server:
    build: Server/.
    ports:
      - "33333:33333"
    tty: true
    networks:
      localnet:
        ipv4_address: 192.168.10.3
  client1:
    build: Client/.
    ports:
      - "33334:33333"
    tty: true
    depends_on:
      - server
    networks:
      localnet:
        ipv4_address: 192.168.10.4
  client2:
    build: Client/.
    ports:
      - "33335:33333"
    tty: true
    depends_on:
      - client1
    networks:
      localnet:
        ipv4_address: 192.168.10.5
  client3:
    build: Client/.
    ports:
      - "33336:33333"
    tty: true
    depends_on:
      - client2
    networks:
      localnet:
        ipv4_address: 192.168.10.6
networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/16
