version: "3.9"
services:
  server:
    build: Server/.
    #command: bash -c "java Server 0"
    volumes:
      - .:/usr/src/server
    environment:
      - 'start_range=0'
    ports:
     - "33333:33333"
    tty: true
    networks:
       localnet:
          ipv4_address: 192.168.10.2
networks:
    localnet:
        driver: bridge
        ipam:
          driver: default
          config:
          - subnet: 192.168.10.0/16