#!/bin/bash

sudo ls > /dev/null


REMOTE_ADDRESS='127.0.0.1'
REMOTE_PORT=33333
START_NUMBER=5

Make()
{
    javac -classpath . *.java
}

Server()
{
        Make
        java Server.java $START_NUMBER
}

Client()
{
        Make
        java Client.java $REMOTE_ADDRESS $REMOTE_PORT
}

ShowUsage()
{
        echo 'Make               : Makes all files'
        echo 'client             : starts up the client program'
        echo '  --remote_address : Must include an ip address address'
        echo '                     otherwise it uses the loopback address'
        echo 'server             : starts up the server program'
        echo '  --start_number   : Must include a number to start the server at'
        echo '                     default is 5'
}

SetFlags()
{
        JAVA_I=0
        JAVA_TEMP1="$@"
        JAVA_TEMP=($JAVA_TEMP1)
        for var in "$@"
        do
            case "$var" in
              'server' )
                  START_NUMBER=${JAVA_TEMP[$(($JAVA_I+1))]}
              ;;
              'client' )
                  REMOTE_ADDRESS=${JAVA_TEMP[$(($JAVA_I+1))]}
            esac
            JAVA_I=$(($JAVA_I+1))
        done
}




#Start here
SetFlags $@
case "$1" in
        'make' )
                Make
        ;;
        'client' )
                Client
        ;;
        'server' )
                Server
        ;;
esac

exit 0
